title = "Paulo Salgado - Software Developer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

googleanalytics = "UA-159846793-1"

[params]
    author = "Paulo Salgado"
    info = "Software Developer"
    description = "Hello, World!"
    avatarurl = "images/avatar.jpg"

[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1
    url = "mailto:pjosalgado@gmail.com"
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/paulosalgado"
[[params.social]]
    name = "GitLab"
    icon = "fab fa-gitlab fa-2x"
    weight = 3
    url = "https://gitlab.com/paulosalgado"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/paulosalgado"
